AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API for ChickChat application
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs4.3
      Role: arn:aws:iam::652859276071:role/api-role
      CodeUri: s3://chickchat-artifact/api_backend.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: any
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
      TableName: chickchat
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 5
